### ISSUE TITLE
crash with last actually additions version

### ISSUE THREAD

**Issue by 0Navis0** [XDjackieXD/OpenRadio#13]
I get this crash the last ActuallyAdditions version, it seems that something goes wrong with OpenRadio. http://pastebin.com/ZQhBaDw7

**Comment by XDjackieXD** [comment]
Ellpeck told me earlier today that he changed the API and that I should be fine. Apparently I'm not xD
Give me a few minutes to fix this...

**Comment by 0Navis0** [comment]
Okay no problems XD

**Comment by XDjackieXD** [comment]
fixed with version 0.9.3. This requires API version 28 (either use Actually Additions unstable r71-260 or higher which can be found at https://ci.chaosfield.at or download the r71 stable build from there (the build on Jenkins includes the new API changes. Curseforge downloads will only have the new API version with r72 or newer)).
If you don't want to update your ActAdd version it won't break anything but will disable ActAdd integration until you update it.

**Comment by 0Navis0** [comment]
Thanks for the update. ;)

**Comment by 0Navis0** [comment]
The crash still happens. :(

**Comment by XDjackieXD** [comment]
sry... I will be looking into it.
mind posting the new crashlog?

**Comment by XDjackieXD** [comment]
I know what causes this.
The Java compiler compiles my version check "Integer.parseInt(ActuallyAdditionsAPI.API_VERSION)" to "if(Integer.parseInt("28") >= Init.minActAddVersion)" >.>
